-- Postgres baseline migration.
-- This file creates the final schema equivalent to applying all SQLite
-- migrations 000001 through 000016. New Postgres deployments should start here.

CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    color VARCHAR(7) DEFAULT '#3B82F6',
    description TEXT,
    parent_id INTEGER,
    level INTEGER DEFAULT 1 CHECK (level >= 1 AND level <= 3),
    sort_order INTEGER DEFAULT 0,
    path VARCHAR(255) DEFAULT '/',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE CASCADE,
    UNIQUE(name, parent_id)
);

CREATE INDEX idx_categories_parent_id ON categories(parent_id);
CREATE INDEX idx_categories_level ON categories(level);
CREATE INDEX idx_categories_deleted_at ON categories(deleted_at);

CREATE TABLE tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    category_id INTEGER NOT NULL,
    due_date TIMESTAMP WITH TIME ZONE NOT NULL,
    estimated_minutes INTEGER NOT NULL,
    is_completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMP WITH TIME ZONE,
    is_suspended BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_tasks_category_id ON tasks(category_id);
CREATE INDEX idx_tasks_due_date ON tasks(due_date);
CREATE INDEX idx_tasks_is_completed ON tasks(is_completed);
CREATE INDEX idx_tasks_completed_at ON tasks(completed_at);
CREATE INDEX idx_tasks_deleted_at ON tasks(deleted_at);

CREATE TABLE timelogs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER DEFAULT 1,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    category_id INTEGER NOT NULL,
    task_id INTEGER,
    remark TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE INDEX idx_timelogs_category_id ON timelogs(category_id);
CREATE INDEX idx_timelogs_task_id ON timelogs(task_id);
CREATE INDEX idx_timelogs_deleted_at ON timelogs(deleted_at);

CREATE TABLE constraints (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    end_reason TEXT,
    punishment_quote TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    metric_id INTEGER,
    metric_operator TEXT,
    metric_target_value DOUBLE PRECISION
);

CREATE INDEX idx_constraints_is_active ON constraints(is_active);
CREATE INDEX idx_constraints_start_date ON constraints(start_date);
CREATE INDEX idx_constraints_end_date ON constraints(end_date);

CREATE TABLE webauthn_credentials (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id BYTEA NOT NULL UNIQUE,
    public_key BYTEA NOT NULL,
    attestation_type TEXT NOT NULL,
    transport TEXT NOT NULL,
    device_name TEXT,
    user_present BOOLEAN NOT NULL DEFAULT FALSE,
    user_verified BOOLEAN NOT NULL DEFAULT FALSE,
    backup_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    backup_state BOOLEAN NOT NULL DEFAULT FALSE,
    authenticator_aaguid BYTEA NOT NULL,
    authenticator_sign_count INTEGER NOT NULL DEFAULT 0,
    authenticator_clone_warning BOOLEAN NOT NULL DEFAULT FALSE,
    authenticator_attachment TEXT NOT NULL,
    attestation_client_data_json BYTEA NOT NULL,
    attestation_client_data_hash BYTEA NOT NULL,
    attestation_authenticator_data BYTEA NOT NULL,
    attestation_public_key_algorithm INTEGER NOT NULL,
    attestation_object BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_webauthn_credentials_deleted_at ON webauthn_credentials(deleted_at);

CREATE TABLE temp_passwords (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password_hash TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_temp_passwords_expires_at ON temp_passwords(expires_at);
CREATE INDEX idx_temp_passwords_deleted_at ON temp_passwords(deleted_at);

CREATE TABLE metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    metric_type TEXT NOT NULL DEFAULT 'numeric',
    unit TEXT NOT NULL DEFAULT 'count',
    current_value DOUBLE PRECISION,
    last_recorded_at TIMESTAMP WITH TIME ZONE,
    extra TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE metric_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_id INTEGER NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    source TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (metric_id) REFERENCES metrics(id)
);

CREATE TABLE audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id INTEGER,
    source TEXT NOT NULL,
    request_id TEXT,
    payload TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_source ON audit_logs(source);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

-- Seed default categories. On a fresh database these receive IDs 1 through 7.
INSERT INTO categories (name, color, description, level, path) VALUES
('工作', '#EF4444', '工作相关的时间记录', 1, '/'),
('学习', '#10B981', '学习和培训时间', 1, '/'),
('会议', '#F59E0B', '各种会议时间', 1, '/'),
('开发', '#8B5CF6', '软件开发和编程', 1, '/'),
('休息', '#6B7280', '休息和放松时间', 1, '/'),
('运动', '#F97316', '体育锻炼和健身', 1, '/'),
('其他', '#6366F1', '其他未分类活动', 1, '/');
